apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  containers:
    - name: sample-app
      image: karthequian/helloworld:latest
      imagePullPolicy: IfNotPresent 
      ports:
        - containerPort: 80
