apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 40002
  selector:
    app: mariadb
status:
  loadBalancer: {}
