kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-02
  labels:
    type: local
spec:
  storageClassName: volume-02
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k0s/storage/data/pv02"
