apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    extraArgs:
      service-node-port-range: 40000-40100
  workerProfiles:
    - name: min-eviction
      values:
        evictionHard:
          memory.available: "500Mi"
          nodefs.available: "2Gi"
          imagefs.available: "2Gi"
        evictionMinimumReclaim:
          memory.available: "250Mi"
          nodefs.available: "1Gi"
          imagefs.available: "1Gi"
  telemetry:
    enabled: false